package app.mobius.service

import app.mobius.domain.entity.security.AppAuthSessionToken
//import app.mobius.domain.entity.security.AppAuthorization
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service
import java.util.*

@Service
class ApplicationAuthorizationService {

    /**
     * Get the bean called appCredentialsRepository, which is auto-generated by Spring,
     * we will use it to handle the data
     */
//    @Autowired
//    private lateinit var appCredentialsRepository: AppCredentialsRepository

    fun getAppAuthorizationSessionToken(
//            appAuthorizationCredentials: AppAuthorization
    ): AppAuthSessionToken {
//        TODO: Impl
        return AppAuthSessionToken(UUID.randomUUID(), "", 0)
    }

    fun checkAppAuthorizationSessionToken(appAuthSessionToken: AppAuthSessionToken) : Boolean {
//        TODO: Impl
        return true
    }

}
