package app.mobius.service

import app.mobius.data.dao.AppCredentialsRepository
import app.mobius.domain.entity.AppAuthSessionToken
import app.mobius.domain.entity.AppAuthorizationCredentials
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service
import java.util.*

@Service
class ApplicationAuthorizationService {

    /**
     * Get the bean called appCredentialsRepository, which is auto-generated by Spring,
     * we will use it to handle the data
     */
    @Autowired
    private lateinit var appCredentialsRepository: AppCredentialsRepository

    fun getAppAuthorizationSessionToken(
            appAuthorizationCredentials: AppAuthorizationCredentials
    ): AppAuthSessionToken {
//        TODO
        return AppAuthSessionToken(UUID.randomUUID(), "", 0)
    }

}
