package app.mobius.service

import app.mobius.data.dao.PersonRepository
import app.mobius.data.katharsis.IdentityResourceRepository
import app.mobius.domain.entity.Person
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service
import java.util.*

@Service
class PersonService {

    /**
     * Get the bean called personRepository, which is auto-generated by Spring,
     * we will use it to handle the data
     */
    @Autowired
    private lateinit var personRepository: PersonRepository

    @Autowired
    private lateinit var identityResourceRepository: IdentityResourceRepository

    fun createPerson(person: Person) : String {
        personRepository.save(person)
        return "Saved"
    }

    fun getPeople() : List<Person> {
        return personRepository.findAll()
    }

 /*   fun getIdentities() : List<Person> {
        return identityResourceRepository.findAll()
    }*/

    fun getPersonById() : Person {
        return Person() //TODO
    }

}
