package app.mobius.signUp.service

import app.mobius.signUp.data.repository.PersonJpaRepository
import app.mobius.domain.entity.Person
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

@Service
class SignUpService {

    /**
     * Get the bean called personRepository, which is auto-generated by Spring,
     * we will use it to handle the data
     */
    @Autowired
    private lateinit var personJpaRepository: PersonJpaRepository

    fun getPeople() : List<Person> {
        return personJpaRepository.findAll()
    }

    fun getPersonById() : Person {
        return Person() //TODO
    }

    fun createPerson(person: Person) : String {
        personJpaRepository.save(person)
        return "Saved"
    }

}