package app.mobius.controller

import app.mobius.data.PersonRepository
import app.mobius.domain.entity.Person
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.*

/**
 * URL's start with /demo (after Application path)
 */
@RestController
@RequestMapping("/people")
class PersonController {

    /**
     * Get the bean called personRepository, which is auto-generated by Spring,
     * we will use it to handle the data
     */
    @Autowired
    private lateinit var personRepository: PersonRepository

    @PostMapping("/add")    // Map ONLY POST Requests
    @ResponseBody
    fun addPerson(/*@RequestParam person: Person*/) : String  {
//        personRepository.save(person)
        personRepository.save(Person())
        return "Saved"
    }
    /**
     * @return JSON or XML with the people
     */
    @GetMapping("/all")
    @ResponseBody
    fun getPeople() : List<Person> {
        return personRepository.findAll()
    }

    /*@GetMapping("/person")
    fun getPerson(): Person = TODO()*/


}
